module.exports = {
  sendVerifyEmailToken: require("./sendVerifyEmailToken"),
  sendAccountRecoveryToken: require("./sendAccountRecoveryToken"),
  sendVerificationToken: require("./sendVerificationToken"),
  sendWelcomeEmail: require("./sendWelcomeEmail"),
  sendL3ApprovalEmail: require("./sendL3ApprovalEmail"),
  sendNewDeviceVerification: require("./sendNewDeviceVerification"),
  sendReceiveCoinsEmail: require("./sendReceiveCoinsEmail"),
  // sendShibDistributionEmail: require("./sendShibDistributionEmail"),
  // sendPCMail1: require("./pcMail1"),
  // sendPCMail2: require("./pcMail2"),
  // sendPCMail3: require("./pcMail3"),
  // sendPCMail4: require("./pcMail4"),
  // sendPCMail5: require("./pcMail5"),
  // sendPCMail6: require("./pcMail6"),
  // sendPCMail7: require("./pcMail7"),
  // sendPCMail8: require("./pcMail8"),
  // sendPCMail9: require("./pcMail9"),
  // sendPCMail10: require("./pcMail10"),
  // sendPCMail11: require("./pcMail11"),
  // sendPCMail12: require("./pcMail12"),
  // sendPCMail13: require("./pcMail13"),
  // sendPCMail14: require("./pcMail14"),
  // sendPCMail15: require("./pcMail15"),
  // sendPCMail16: require("./pcMail16"),
  // sendPCMail17: require("./pcMail17"),
  // sendPCMail18: require("./pcMail18"),
  // sendPCMail19: require("./pcMail19"),
  // sendPCMail20: require("./pcMail20"),
  // sendEmailIssueEmail: require("./sendEmailIssueEmail"),
  // sendCxMail1: require("./CxMail1"),
  // sendCxMail2: require("./CxMail2"),
  // sendCxMail3: require("./CxMail3"),
  // sendCxMail4: require("./CxMail4"),
  // sendCxMail5: require("./CxMail5"),
  // sendCxMail6: require("./CxMail6"),
  // sendCxMail7: require("./CxMail7"),
  // sendCxMail8: require("./CxMail8"),
  // sendCxMail9: require("./CxMail9"),
};
